### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [troglobit/editline#12]
I would like to point out that an identifier like "[`__EDITLINE_H__`](https://github.com/intelxed/xed/blob/fcd2d41b2bd8802eed4e620a6836795fbd7ad919/include/public/xed/xed-interface.h#L25 "Update candidate")" [does eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by troglobit** [comment]
Fixed in a70a933

**Comment by elfring** [comment]
Thanks for [your adjustment of affected include guards](https://github.com/troglobit/editline/commit/a70a9336982c2ece1251ffa10ce07f5b4b516131 "Modify header guards").
