### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [troglobit/editline#13]
[An extra null pointer check is not needed](http://pubs.opengroup.org/onlinepubs/9699919799/functions/free.html "Do I need to check for null before free p?") in functions like the following.
- [search_hist](https://github.com/troglobit/editline/blob/2a3575495ad779185459a3294ad857ea7208c899/src/editline.c#L593)
- [save_yank](https://github.com/troglobit/editline/blob/059d97d7a939019ccafe901c82a6d2d474dca62f/src/editline.c#L679)

**Comment by troglobit** [comment]
Won't fix.
