### ISSUE TITLE
strdup implementation has off-by-one error

### ISSUE THREAD

**Issue by Buzzzz** [troglobit/editline#17]
In src/sysunix.c there is this:

```
#ifndef HAVE_STRDUP
/* Return an allocated copy of a string. */
char *strdup(const char *p)
{
    char *new = malloc(sizeof(char) * strlen(p));
```

This forgets to malloc the terminating NUL for the string and causes undefined behavior for the subsequent strcpy.

This should be

`malloc(strlen(p) + 1);`

Note that multiplying by sizeof(char) is considered silly, since it is 1 by definition in the C Standard.

**Comment by troglobit** [comment]
That old piece of code ... not sure if it's even worth keeping.  Did you just stumble upon this or are you actively using editline on a target without `strdup()`?

**Comment by troglobit** [comment]
OK, according to the RTEMS 5.0.0 POSIX compliance guide it supports `strdup()`, so then I'll just remove that code path.

**Comment by troglobit** [comment]
Fixed, in my patch queue pending new completion API (FSF compat)
