### ISSUE TITLE
Does editline support context specific auto-complete?

### ISSUE THREAD

**Issue by ChrisNisbet01** [troglobit/editline#3]
Hi
I've just been looking at this library for use in a simple CLI application.
I see that there is some support for supplying custom auto-complete functions so that (for example) the application can auto-complete commands from a fixed set of command names.
When I try out the example cli application, I see that auto-complete searches the same list with each and every argument.
What I'd like to do is vary the auto-complete function depending on the arguments already entered by the user so that (for example) auto-completing the second argument in a command searches one list if the first argument is 'a', and a different list if the first argument is 'b'. 
Is this possible out of the box with this library? Is there a way to obtain the arguments already entered so that auto-complete can be made more context specific?
Thanks

**Comment by troglobit** [comment]
Simple answer: no.

I've been using it for a CLI myself, with autocompletion. For that application I built what I needed outside of editline.  I have been thinking about building a generic CLI library on top of editline for quite some time now. Never really got around to it though.

**Comment by ChrisNisbet01** [comment]
No problem.
Thanks for the prompt response.
