### ISSUE TITLE
Pressing Ctrl+C when searching sends SIGINT after next command

### ISSUE THREAD

**Issue by abitmore** [troglobit/editline#31]
Steps to reproduce:
1. type anything in input mode, then press ctrl+R, enter search mode
2. type anything, press ctrl+C
3. type a command, press ENTER
4. result: the program got a SIGINT, which is unexpected IMHO.

Maybe this change can fix it?https://github.com/troglobit/editline/pull/28/commits/2b75e9eba4d2e2c5eaae2314de962c28be91ddac#diff-532aa92b0f7db9561ed48bb41ec87506R694

**Comment by troglobit** [comment]
We can escape recording Ctrl-C when searching, that's easier and we now behave more like GNU Readline.  Thanks for reporting this!
