### ISSUE TITLE
Support for Latin-1?

### ISSUE THREAD

**Issue by michaelbrunnbauer** [troglobit/editline#33]
Is it possible editline only supports UTF8? 

As you may know, mysql now only supports editline and this causes problems with german umlaut characters on systems with LC_CTYPE=de_DE or de_DE.iso88591 instead of de_DE.utf8

**Comment by troglobit** [comment]
I'm sorry, but you're not the first to get confused by libeditline vs libedit.  Please see issue #11 for details.
