### ISSUE TITLE
Cannot find sgstat.h or modes.h.

### ISSUE THREAD

**Issue by h3adshotzz** [troglobit/editline#36]
This is not an issue with the compilation of the library, more of an issue with that I cannot find where these headers reside, I cannot find much information about them, but it compiles perfectly fine.
```c
#include <sgstat.h>
#include <modes.h>
```

**Comment by h3adshotzz** [comment]
I'm working on a project where I'd like editline to be linked, so I'm attempting to build it with Meson - and that's where the issue arises.

**Comment by troglobit** [comment]
Those are standard header files in OS-9, which is unlikely what you want to include in your build ;-)
