### ISSUE TITLE
The process that uses editline does not respect CTRL+Z

### ISSUE THREAD

**Issue by lilastic** [troglobit/editline#47]
When I press `CTRL+Z` to suspend the process that runs `editline` (I'm in Linux), it doesn't react. FYI, when using the `readline` library everything works as expected (i.e. the process would have been suspended and the prompt returns to the terminal). How can this be fixed? Thanks!

**Comment by troglobit** [comment]
Editline is not a replacement for GNU readline, it has its own history and defaults.   Please see the output from ./configure --help.
