### ISSUE TITLE
fileman.c example. Error free(): double free detected in tcache 2

### ISSUE THREAD

**Issue by Morphlng** [troglobit/editline#56]
## Error Description
So I'm using `rl_attempted_completion_function` to add my own keyword completion, but ever since that the **filepath completion** doesn't work as expected, it will crash with free(): double free detected in tcache 2. I thought it was my problem, so I tried the fileman.c given in the example, but it ended up the same. 
Comment out the binding to rl_attempted_completion_function, then it will work normally. So I guess there's something wrong with executing that function.

## How to trigger
If you input ./ \<tab>, then it will crash, but if you quote the path it works, e.g "/usr \<tab>, it will show /usr/lib.

## Sysinfo
System: Lubuntu 20.04
GCC Version: 9.3.0

**Comment by troglobit** [comment]
Thank you for the report.
