### ISSUE TITLE
Prompt not displayed on non-interactive sessions, inconsistent with GNU readline

### ISSUE THREAD

**Issue by lf-** [troglobit/editline#65]
On editline-1.17.1:

```
co/nix » echo '1+1' | LD_PRELOAD=result/lib/libreadline.so nix repl --quiet | cat
nix-repl> 1+1
2


co/nix » echo '1+1' | nix repl --quiet | cat
Failed tcsetattr(TCSADRAIN): Inappropriate ioctl for device
Failed tcsetattr(TCSADRAIN): Inappropriate ioctl for device
2
```

Confirmed by inspection of the code: when `!isatty()`, prompts aren't printed.

**Comment by troglobit** [comment]
This is by design.  Editline is not an attempt at being a readline clone.

**Comment by 9999years** [comment]
From the README, "[editline] is call compatible with the [FSF readline](http://www.gnu.org/software/readline/) library, but at a fraction of the size, and as a result fewer features" -- it's call compatible, but it's not intended to be a drop-in replacement? I'm not sure I understand.

**Comment by troglobit** [comment]
Old description, that should be rephrased.  It's call compatible in the sense that `readline()` returns the read line and it has a familiar API, but other than that the evolved behavior of the library diverged to form its own path.
